# User config
author: "365ML HQ"
tagline: "One small machine learning project a day"
description: "Just a small site to keep me motivated with byte-sized projects in all data-related domains"
keywords: "Machine learning"
email: ""
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed