# User config
author: "365ML HQ"
tagline: "One small machine learning project a day"
description: "Just a regular dude doing one byte-sized ML notebook a day, for a year."
keywords: "Machine learning"
email: ""
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed